# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "lightmix-0.26.0-SpCovCZcBQBv6Mc5F-Jb99lcspkm-5Bo3m3nowSHKoW3";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix/archive/refs/tags/0.26.0.tar.gz";
      hash = "sha256-zB4JTv8x9ODVK4ANEDpq0lDthNhOH6Z+y4ww/bQT9Yg=";
    };
  }
  {
    name = "meters-0.1.0-EsVLmyDGAACE-3GCOOjWTlD5YV2ZVUXIxeweZgj5gl5H";
    path = fetchgit {
      url = "https://github.com/haruki7049/meters";
      rev = "567f70a073fc861418f1dc02d05d08de5957e91d";
      hash = "sha256-xyKazXuRU3do+5JnCgpkyZElEmBT59B5COsyrHDrrQg=";
    };
  }
  {
    name = "resonator-0.1.0-_vVfzntkAADp3E5l_J_eO8iMSPBnFO_3-SwYredkPCzO";
    path = fetchgit {
      url = "https://github.com/haruki7049/resonator";
      rev = "e61422fe5325678a57e9001be8b200c398d30d67";
      hash = "sha256-xCdIkJBwv6WC0fTdnhYixZA/SRpPFjc6qXNJhcspgag=";
    };
  }
  {
    name = "riff_zig-2.0.0-J7H0A9npTQCZnbwyGH2Ue8AJHRQbEU1T6Ijio7rRdoRN";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/2.0.0.tar.gz";
      hash = "sha256-+Dl0rbYtQsyUHPACEu6duuiBQRvgD9k2VvLIPe4pvko=";
    };
  }
  {
    name = "zigggwavvv-2.0.0-iR5xWutnAgCm4osN3wN-ooN5SNj62hGCBM6yMC4EzRMc";
    path = fetchzip {
      url = "https://github.com/haruki7049/zigggwavvv/archive/refs/tags/2.0.0.tar.gz";
      hash = "sha256-nvCfAWEqgy57+o/z41DGjwFzcYWVbmjbfoLtLyutQew=";
    };
  }
]
