# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "lightmix-0.26.0-SpCovCZcBQBv6Mc5F-Jb99lcspkm-5Bo3m3nowSHKoW3";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix/archive/refs/tags/0.26.0.tar.gz";
      hash = "sha256-zB4JTv8x9ODVK4ANEDpq0lDthNhOH6Z+y4ww/bQT9Yg=";
    };
  }
  {
    name = "phrases-0.1.0-m8uXUcJ5AADNbVNrVA3b_IUJpXPL_dt4kXmkRWEacj9n";
    path = fetchgit {
      url = "https://github.com/haruki7049/phrases";
      rev = "524d42fa408e0834efcd2835e0e9a849ea1bd238";
      hash = "sha256-/JtfGRmsIg5+cx5KIuLTLqgrxS6H3/Dj0/aglpwqNEc=";
    };
  }
  {
    name = "resonator-0.1.0-_vVfzphiAACB2Sl3XGOZoDx7rICvskMPRRnjU4M62hLN";
    path = fetchgit {
      url = "https://github.com/haruki7049/resonator";
      rev = "d429ffaaa591c2f2407661e21965b08bbdfb2ca6";
      hash = "sha256-BfopRTnlodTaPmozS2HuwJ64aL7RqH4yVX6F6G/9Nfo=";
    };
  }
  {
    name = "riff_zig-2.0.0-J7H0A9npTQCZnbwyGH2Ue8AJHRQbEU1T6Ijio7rRdoRN";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/2.0.0.tar.gz";
      hash = "sha256-+Dl0rbYtQsyUHPACEu6duuiBQRvgD9k2VvLIPe4pvko=";
    };
  }
  {
    name = "zigggwavvv-2.0.0-iR5xWutnAgCm4osN3wN-ooN5SNj62hGCBM6yMC4EzRMc";
    path = fetchzip {
      url = "https://github.com/haruki7049/zigggwavvv/archive/refs/tags/2.0.0.tar.gz";
      hash = "sha256-nvCfAWEqgy57+o/z41DGjwFzcYWVbmjbfoLtLyutQew=";
    };
  }
]
