{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs:
    let
      # The only repository-specific line: the package name.
      name = "sequencer";
    in
    inputs.flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "aarch64-darwin"
      ];

      imports = [
        inputs.treefmt-nix.flakeModule
      ];

      perSystem =
        {
          config,
          lib,
          pkgs,
          ...
        }:
        let
          # The package is defined only once a build.zig exists.
          hasBuild = builtins.pathExists ./build.zig;
          # Zig dependencies are pre-fetched from `.deps.nix` (generated by
          # `zon2nix`) because the sandboxed build has no network access.
          # Repositories without dependencies have no `.deps.nix`.
          hasDeps = builtins.pathExists ./.deps.nix;

          ZIG = pkgs.zig_0_16;
          nativeBuildInputs = [
            # Compiler
            ZIG

            # LSP
            pkgs.nil
            pkgs.zls

            # zon2nix
            pkgs.zon2nix
          ];

          package = pkgs.stdenv.mkDerivation {
            inherit name;
            src = lib.cleanSource ./.;
            doCheck = true;

            nativeBuildInputs = nativeBuildInputs ++ [ ZIG.hook ];

            postPatch = ''
              ${lib.optionalString hasDeps "ln -s ${pkgs.callPackage ./.deps.nix { }} zig-pkg"}

              # Remove NIX_CFLAGS_COMPILE because zig cannot understand it
              unset NIX_CFLAGS_COMPILE
            '';
          };
        in
        {
          treefmt = {
            projectRootFile = ".git/config";

            # Nix
            programs.nixfmt.enable = true;

            # Zig
            programs.zig.enable = true;
            settings.formatter.zig.command = lib.getExe ZIG;

            # GitHub Actions
            programs.actionlint.enable = true;

            # Markdown
            programs.mdformat.enable = true;

            # Shell Scripts
            programs.shellcheck.enable = true;
            programs.shfmt.enable = true;
          };

          packages = lib.optionalAttrs hasBuild {
            ${name} = package;
            default = package;
          };

          checks = lib.optionalAttrs hasBuild {
            ${name} = package;
          };

          devShells.default = pkgs.mkShell {
            inherit nativeBuildInputs;

            inputsFrom = [
              config.treefmt.build.devShell
            ];

            shellHook = ''
              # Remove NIX_CFLAGS_COMPILE because zig cannot understand it
              unset NIX_CFLAGS_COMPILE
            '';
          };
        };
    };
}
